-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    first_name: james
    last_name: bond
    ip_address: 192.168.1.6
    file_path: /etc/hosts
    web_dependencies:
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
      - python-mysqldb
    sql_dependencies:
      - python
      - python-mysqldb
    array_of_numbers:
      - 12
      - 34
      - 06
      - 34
  tasks:
  - debug:
      msg: 'The name is {{ last_name }}! {{ first_name }} {{ last_name }}!'
  - debug:
      msg: 'The name is {{ last_name  | title }}! {{ first_name | title }} {{ last_name  | title }}!'
  - debug:
      msg: 'Lowest = {{ array_of_numbers  | min }}'
  - name: Install dependencies
    apt: name='{{ item }}' state=installed
    with_items: '{{ web_dependencies | union(sql_dependencies) }}'
  - name: Install dependencies
    file:
      path: /tmp/random_file"{{ 1000 | random }}"
      state: touch
    debug:
      msg: IP Address = {{ ip_address | ipaddr  }}
     debug:
      msg: File Name = {{file_path | basename}}
