-
  name: Test Connectivity
  hosts: web_server
  vars:
    ansible_ssh_pass: "{{ lookup('csvfile', 'web_server file=credentials.csv delimiter=,') }}"
    ansible_ssh_pass2: "{{ lookup('ini', 'password section=web_server file=credentials.ini') }}"
  tasks:
  - name: Ping target host
    ping:
           data: "Test"
