- name: a simple python web application
  hosts: db_and_web_server1, db_and_web_server2
  tasks:
    - name: install all the dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        
