-
  name: Deploy a web application
  hosts: db_and_web_server
  vars:
    db_name: employee_db
    db_user: db_user
    db_password: Passw0rd 
  roles:
  - python
  - mysql_db
  - flash_web
  #  - include: tasks/deploy_db.yml
  #  - include: tasks/deploy_web.yml

        
